apiVersion: apps/v1
kind: Deployment
metadata:
  name: load
  labels:
    service: load
spec:
  replicas: 1
  selector:
    matchLabels:
      service: load
  template:
    metadata:
      labels:
        service: load
    spec:
      containers:
      - name: load
        env:
          - name: HOST
            value: "https://robot-shop.dev.asserts.ai"
          - name: NUM_CLIENTS
            value: "5"
          - name: SILENT
            value: "1"
          - name: ERROR
            value: "0"
#          - name: FAILURE_HOUR
#            value: "10"
          - name: FAILURE_FROM_MINUTE
            value: "0"
          - name: FAILURE_TILL_MINUTE
            value: "15"
        image: asserts/robot-shop-rs-load:1.0.2
        resources:
          limits:
            cpu: 1000m
            memory: 800Mi
          requests:
            cpu: 500m
            memory: 400Mi
