apiVersion: v1
kind: Service
metadata:
  name: dispatch
  labels:
    service: dispatch
    app: robot-shop
spec:
  ports:
  - name: http-metrics
    port: 8080
    targetPort: 8080
  selector:
    service: dispatch
