apiVersion: v1
kind: Service
metadata:
  name: dispatch
  labels:
    service: dispatch
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: dispatch
