{{- if .Values.tracing.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service : es-jaeger
  name: es-jaeger
  namespace: monitoring
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      service : es-jaeger
  serviceName: es-jaeger
  template:
    metadata:
      labels:
        service : es-jaeger
    spec:
      initContainers:
      - name: create
        image: busybox:1.28
        command: [ 'mkdir', '-p', '/usr/share/elasticsearch/data/nodes/' ]
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: elasticsearch-data
      - name: file-permissions
        image: busybox:1.28
        command: [ 'chown', '-R', '1000:1000', '/usr/share/elasticsearch/' ]
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: elasticsearch-data
      containers:
        - env:
            - name: cluster.name
              value: es-cluster
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: bootstrap.memory_lock
              value: "false"
          image: elasticsearch:7.17.8
          imagePullPolicy: IfNotPresent
          name: es-jaeger
          ports:
            - containerPort: 9200
              name: http
              protocol: TCP
            - containerPort: 9300
              name: transport
              protocol: TCP
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 150m
              memory: 512Mi
          securityContext:
            privileged: true
            runAsUser: 1000
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-data
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{ if not .Values.openshift }}
        storageClassName: {{ .Values.redis.storageClassName }}
        volumeMode: Filesystem
        {{ end }}
        resources:
          requests:
            storage: 30Gi
{{- end }}
