{{- if .Values.jaeger.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    service: jaeger
    app: robot-shop
  name: jaeger
  namespace: monitoring
spec:
  ports:
    - name: jaeger
      port: 14250
      targetPort: 14250
    - name: jaeger-ui
      port: 16686
      targetPort: 16686
    - name: jaeger-thirft
      port: 14268
      targetPort: 14268
  selector:
    service: jaeger
{{- end }}
