---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
data:
  collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    exporters:
      prometheus:
        namespace: default
        endpoint: 0.0.0.0:8889
      otlp:
        endpoint: http://jaeger.monitoring.svc.cluster.local:4317
        tls:
          insecure: true

    processors:
      assertsprocessor:
        asserts_server:
          endpoint: {{ .Values.otelcollector.assertsServer }}
          user: {{ .Values.otelcollector.assertsUser }}
          password: {{ .Values.otelcollector.assertsPassword }}
        asserts_env: {{ .Values.otelcollector.assertsEnv }}
        asserts_site: {{ .Values.otelcollector.assertsSite }}
        trace_rate_limit_per_service_per_request: {{ .Values.otelcollector.tracesPerRequest }}
        span_attribute_match_regex:
          "rpc.system": "aws-api"
          "rpc.service": "(Sqs)|(DynamoDb)"
        request_context_regex:
          - attr_name: "http.route"
            regex: "(.+)"
          - attr_name: "http.url"
            regex: "https?://.+?(/.+)"
        attributes_as_metric_labels:
          - "rpc.system"
          - "rpc.service"
          - "rpc.method"
          - "aws.table.name"
          - "aws.queue.url"
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [assertsprocessor]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          exporters: [prometheus]
        logs:
          receivers: [otlp]
          exporters: [otlp]
