apiVersion: v1
kind: Service
metadata:
  labels:
    service: pushgateway
    app: robot-shop
    type: infra
  name: pushgateway
spec:
  ports:
  - name: http-metrics
    port: 9091
    targetPort: 9091
  selector:
    service: pushgateway
