apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    service: ratings
    app: robot-shop
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: ratings

