---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics
  labels:
    release: {{ .Values.serviceMonitor.releaseLabel }}
    app: robot-shop
spec:
  selector:
    matchLabels:
      app: robot-shop
  namespaceSelector:
    any: true
  endpoints:
    - port: http
    - port: http-metrics
